filename1="FinalProjectFiles/handwriting_test_set_labels.txt"
filename2="FinalProjectFiles/handwriting_test_set.txt"
filename3="FinalProjectFiles/handwriting_training_set_labels.txt"
filename4="FinalProjectFiles/handwriting_training_set.txt"